# Generated by Django 5.0.3 on 2024-05-09 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0003_alter_produto_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='estilo',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
