# Generated by Django 5.0.3 on 2024-05-09 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0005_alter_produto_estilo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='estilo',
            field=models.CharField(choices=[('ELEGANTE', 'Elegante'), ('TROPICAL', 'Tropical'), ('FLORIDO', 'Florido')], default='', max_length=100),
        ),
    ]
