# Generated by Django 5.0.3 on 2024-05-09 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0006_alter_produto_estilo'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='estoque',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
