# Generated by Django 5.0.4 on 2024-05-20 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0008_alter_cliente_options_alter_cliente_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='username',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
