# Generated by Django 5.0.4 on 2024-05-27 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0009_alter_cliente_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='quantidade_estoque',
            field=models.IntegerField(default=0),
        ),
    ]
