# Generated by Django 5.0.6 on 2024-05-29 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0011_delete_itemaluguel'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='publicado',
            field=models.BooleanField(default=False),
        ),
    ]
