# Generated by Django 5.0.6 on 2024-06-04 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0012_produto_publicado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='categoria',
            field=models.CharField(choices=[('PRATO RASO', 'Prato Raso'), ('GUARDANAPO', 'Guardanapo'), ('TALHER', 'Talher'), ('TACAS', 'Tacas'), ('TRILHOS DE MESA', 'Trilhos de Mesa'), ('SOUSPLAT', 'Sousplat'), ('JOGO AMERICANO', 'Jogo Americano'), ('CHA E CAFE', 'Cha e Cafe'), ('PRATO SOBREMESA', 'Prato Sobremesa'), ('PORTA GUARDANAPO', 'Porta Guardanapo')], default='', max_length=150),
        ),
    ]
