# Generated by Django 5.0.6 on 2024-06-04 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0013_alter_produto_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='estoque',
        ),
    ]
